plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.9'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.tdd'
version = '1.1.1'
description = 'book'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation "com.google.protobuf:protobuf-java:4.35.0"

    //bc
    implementation 'ru.tdd.bc:imp:1.1.1'
    implementation 'ru.tdd.bc:database:1.1.1'
    implementation 'ru.tdd.bc:security:1.1.1'
    implementation 'ru.tdd.bc:exceptions:1.1.1'
    implementation 'ru.tdd.bc:security:1.1.1'
    implementation 'ru.tdd.bc:proto:1.1.1'
    implementation 'ru.tdd.bc:kafka-core:1.1.1'
    implementation 'ru.tdd.bc:openapi:1.1.1'
    implementation 'ru.tdd.bc:redis:1.1.1'

    //jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'

    //database
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    //kafka
    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    //testcontainers
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.testcontainers:kafka'

    //security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    //web
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    //redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    //flyway
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    //openapi
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.15'

    //test
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    //mapstruct
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.incremental = true
    options.compilerArgs += [
            '-Amapstruct.defaultComponentModel=spring',
            '-Amapstruct.unmappedTargetPolice=IGNORE',
            '-Amapstruct.suppressGeneratorTimestamp=true',
            '-Amapstruct.suppressGeneratorVersionInfoComment=true'
    ]
}
